# Generated by Django 4.0 on 2021-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
