# Generated by Django 4.0 on 2021-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postform',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
